targets:
  $default:
    builders:
      localizable|localizable:
        enabled: true
        options:
          hideOutput: false

builders:
  localizable:
    import: "package:localizable/builder.dart"
    builder_factories: ["generateLocalizations"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
